# -*- coding: utf-8 -*-
"""biaMenosCompleto.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hOC6oeIBv6FuNQrg3Gh5BtFKVJro1FGl
"""

#Desenvolvido por BIA, 05/2021
pip3 install biopython #instalação da biblioteca Biopython no colab

import Bio #Importando todo pacote

#Apresentação da sequência do nucleotídeos 
from Bio import SeqIO #Importando o modolo SeqIO da biblioteca Bio
from Bio.SeqRecord import SeqRecord
#Modolo SeqIO é um modolo utilizado para leitura e gravação de arquivos em diversos formatos
for i in SeqIO.parse("NC_009934.gbk", "genbank"):
  SeqIO.convert("NC_009934.gbk", "genbank", \
"NC_009934.fasta", "fasta")
  print(i.id,":", i.name, ":" ,i.description, ":",i.seq)